### ISSUE TITLE
FlowPattern does not distinguish between numeric and string fields

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/models#1]
`FlowPattern` accepts field inputs as strings regardless of whether the field is `numeric` (e.g. VLAN ID, TCP port) or `string` (IP/MAC address). 

The proposal is to use something like `StrField` and `NumField` instead. Also, `Field` keyword seems to be more relevant than `Pattern`.

*NOTE:* This will also require having separate models for `Random` and `Counter`

Current:
```python
ip = FlowIpv4(src=FlowPattern(choice='fixed', fixed='1.1.1.1'))
ip = FlowIpv4(src=FlowPattern(choice='list', list=['1.1.1.1', '1.1.1.2']))

vlan = FlowVlan(id=FlowPattern(choice='fixed', fixed='10'))
vlan = FlowVlan(id=FlowPattern(choice='list', list=['10', '11']))
```

Proposed:
```python
ip = FlowIpv4(src=StrField(choice='fixed', fixed='1.1.1.1'))
ip = FlowIpv4(src=StrField(choice='list', list=['1.1.1.1', '1.1.1.2']))

vlan = FlowVlan(id=NumField(choice='fixed', fixed=10))
vlan = FlowVlan(id=NumField(choice='list', list=[10, 11]))
```

**Comment by ajbalogh** [comment]
In the sample a pattern is being assigned to the field.
Also it will be up to the code generator to create whatever names it wants for classes, when the payload gets serialized to json there will be no named pattern, just a choice and a child property that details the choice.

**Comment by ashutshkumr** [comment]
Agree with not having to worry about named pattern when on wire (or serialized to json).

The problem I noticed was that I had to cast the field values to str() while creating the config - this does not affect all use cases though. e.g.

```python
# from scapy
v1 = Dot1Q(id=[1, 3, 5])
# had to use
v2 = FlowVlan(id=NumField(choice='list', list=[str(id) for id in v1.id]))
# instead of
v2 = FlowVlan(id=NumField(choice='list', list=v1.id)) 

```

I figured we might come across more such hiccups.

**Comment by ajbalogh** [comment]
At this time we are only supporting string values for field patterns.
