### ISSUE TITLE
Generated Go stubs should be importable go modules

### ISSUE THREAD

**Issue by parthpower** [open-traffic-generator/models#104]
Go client should be commited back to the repository so that one can import them in their Go project as modules.

The import path can be under `pkg/api/otgclient` and `pkg/api/otgserver` so one can import them on as a module `github.com/open-traffic-generator/models/pkg/api/otgclient` and `github.com/open-traffic-generator/models/pkg/api/otgserver`

pipeline changes would be similar to https://github.com/open-traffic-generator/models/blob/bbe3d6ca1585043abdea2d44ddf2e9d20a8581e7/.github/workflows/workflow.yml#L47-L60

**Comment by ankur-sheth** [comment]
@ashutshkumr I think this is complete with the creation of `gosnappi`.  Mark as closed?
