### ISSUE TITLE
Don't insert Ixia signature by default, make optional

### ISSUE THREAD

**Issue by chrispsommers** [open-traffic-generator/models#106]
Current approach of inserting signature is biased towards a certain style of PGID flow-tracking and could interfere with simple functional tests typical of PTF scripts, e.g.: send a packet into a router and verify it comes out a next-hop port with new MAC headers (and payload is identical to what was specified to be transmitted). I guess this would gate the ability to do flow-tracking, so perhaps flow-tracking is the item which is disabled and signature processing on tx/rx is just one consequence of many (including stats etc.). 

In any case, it'd be nice to document the signature contents/format so users can know what to expect on the output.

**Comment by ajbalogh** [comment]
By default flows will not have instrumentation enabled.  A user of the model/API must explicitly enable flow metrics which depending on implementation may or may not introduce instrumentation into the packet payload (this is covered in the model description).
