### ISSUE TITLE
Ingress Stats Tracking: How to opt out of flow stats, track non-field items like frame size and filter ingress field stats

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/models#16]
Adding @ankur-sheth @winstonliu1111 for inputs if any.

### Context
`Flow` in athena is analogous to `FlowGroup` in IxNetwork, because `Rate`, `Size` and `Duration` can be independently controlled per `FlowGroup` (which internally means, they're mapped to one or more hardware streams). Packet flows belonging to different `PGID`s then constitute what IxNetwork calls `Flow`.

`PGID`s are usually internally used to track statistics for:
- Header / Custom fields
- Non-field items like frame size and `FlowGroup`

IxNetwork, by default, only tracks port statistics.

### Problem
- Currently we do not have a way to specify tracking options for non-field items. Apart from not being able to track statistics per frame-size, this also means we cannot opt out of per `Flow` statistics (even if one doesn't need it).
- Even if we decide to mandate per `Flow` stats, noting that ingress field stats are not `part of` per flow stats, it's not clear from doc how to filter out some rows in returned results.

e.g. From below, at first glance, the filter option should help reduce number of rows (and it does when viewing flow stats). But upon closer examination, it will just affect aggregation value when viewing ingress field stats.

Hence, FlowStatRequest should at least allow filtering based on number of rows (irrespective of whether it's per flow or per field value) 

```
# Two flows are configured, each with 4 incr UDP Source Port values, which repeats across 100 packets.

# Stats per Flow (flow_names=['f1', 'f2'])
flow    frames_rx
f1          100
f2          100

# Stats per Flow (flow_names=['f1'])
flow    frames_rx
f1          100

# Flow stats with "UDP sport" as ingress name (flow_names=['f1', 'f2'])
flow    UDP sport    frames_rx
f1        5000          25
f1        5001          25
f1        5002          25
f1        5003          25
f2        5000          25
f2        5001          25
f2        5002          25
f2        5003          25

# Flow stats with "UDP sport" as ingress name (flow_names=['f1'])
flow    UDP sport    frames_rx
f1        5000          25
f1        5001          25
f1        5002          25
f1        5003          25

# How to get this table ? Stats per UDP Source Port (flow_names=['f1', 'f2'])
UDP sport    frames_rx
5000          50
5001          50
5002          50
5003          50

# How to get this table ? Stats per UDP Source Port 5001 and 5003 (flow_names=['f1', 'f2'])
UDP sport    frames_rx
5001          50
5003          50
```

**Comment by ajbalogh** [comment]
These are agnostic models, please frame your issue in terms of want a user wants to and/or see.
The current design of flow results allows a user to retrieve results for all flows or to select flow results for a subset of flow.
In addition the user can tag individual fields of a packet which can then be used to get a more detailed set of results.

Are there users that need to get a more detailed set of results not just by packet fields but by framesize?

**Comment by ajbalogh** [comment]
In other words i'm not familiar with pgids, port streams, ixnetwork.

**Comment by ashutshkumr** [comment]
> These are agnostic models, please frame your issue in terms of want a user wants to and/or see.
> The current design of flow results allows a user to retrieve results for all flows or to select flow results for a subset of flow.
> In addition the user can tag individual fields of a packet which can then be used to get a more detailed set of results.
> 
> Are there users that need to get a more detailed set of results not just by packet fields but by framesize?

I understand, and that's why `Problem` section only talks about issues with tracking flow results in athena API (code snippet shows the examples as well).

As a summary, 
- It is not clear whether per-ingress-field stats can exist independent of per flow stats (IMHO, it should)
  
  e.g. I only need to see stat rows distributed among UDP source ports 5000, 5001, 5002 and 5003 (4 rows). But if I configure two flows (destined for same rx) with same set of UDP source ports, per current API, it would show me 8 rows (4 UDP rows x 2 flows).

  `NOTE`: I'm not saying this is incorrect behaviour, I'm just saying that there needs to be a way to see stats independent of per-flow stats.


- We should be able to track statistics using non-field items like frame size. I cannot confirm whether there are customers that really need to see stats distributed based on frame size, since I have only seen this used in in-house scripts (hence, the realisation that cases like this exist too).

**Comment by ajbalogh** [comment]
With version 0.4.0 per flow ingress tracking is available using the flow.packet.<header>.<field>.metric_group property.
By default ingress tracking is disabled unless specifically enabled on a per flow basis using teh flow.metrics.enable property.
When a customer requires features such as frame size tracking the model can be extended using the per flow metrics container.
