### ISSUE TITLE
No provision available for SRTE policies, SRTE segmentlist, tunneltlv on bgp

### ISSUE THREAD

**Issue by Rangababu-R** [open-traffic-generator/models#171]
No Provision for the below reference yamls
bgpsrtepolicy.yaml
bgpsrtesegment.yaml
bgpsrtesegmentlist.yaml
bgpstretunneltlv.yaml

Looks like the referencing properties are missed. Please check the other files are being sources in ReDocly

**Comment by ankur-sheth** [comment]
@apratimmukherjee can  you please check if this is still valid?
