### ISSUE TITLE
minimum and maximum keys are generated for ipv4 format property

### ISSUE THREAD

**Issue by Rangababu-R** [open-traffic-generator/models#191]
value:
          type: string
          default: 0.0.0.0
          format: ipv4
          minimum: 0
          maximum: 4294967295

When length is set on a property which format is ipv4 and type string the bundler is generating minimum and maximum keys.

1. length key shall be ignored in bundler for the formats ipv4, ipv6, mac and hex as it would cause an issue in snappi and gosnappi validation.
2. For string type the length shall be converted to minLength and maxLength

**Comment by ajbalogh** [comment]
The bundler should enforce no length keywords (minLength, maxLength, minimum, maximum) on ipv4, ipv6 formats and fail accordingly with an appropriate error message for all invalid types at the end of generation.
