### ISSUE TITLE
Disable the Flow tracking from API

### ISSUE THREAD

**Issue by ldotrg** [open-traffic-generator/models#197]
Is there have method to disable flow tracking by API server?
![image](https://user-images.githubusercontent.com/5992038/143875854-fb7c5edf-baa5-4002-a515-c4bb475d174c.png)

**Comment by ajbalogh** [comment]
Flow tracking is disabled by default in the current version of the otg models as seen here https://github.com/open-traffic-generator/models/blob/1d8a9887ba4e26d7ebcb0fc9f82bcf8fc722a073/artifacts/openapi.yaml#L4511-L4520.

If you are using snappi[ixnetwork] then the code to disable traffic item tracking would be as follows:

```python
f1, f2 = config.flows.flow(name="TxFlow-1").flow(name="TxFlow-2")
f1.metrics.enable = False
f2.metrics.enable = False
```
