### ISSUE TITLE
Increment and Decrement patterns can effectively be merged into one as Counter pattern

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/models#2]
Is there any inherent benefit in having two separate counter patterns, i.e. Increment and Decrement ?

Current:
```python
ip = FlowIpv4(src=FlowPattern(choice='increment', increment=FlowIncrement(start='1.1.1.1', step='0.0.0.1', count=10)))
ip = FlowIpv4(src=FlowPattern(choice='decrement', increment=FlowDecrement(start='1.1.1.10', step='0.0.0.1', count=10)))
```

Proposed:
```python
ip = FlowIpv4(src=FlowPattern(choice='counter', counter=Counter(start='1.1.1.1', step='0.0.0.1', count=10, up=True)))
ip = FlowIpv4(src=FlowPattern(choice='counter', counter=Counter(start='1.1.1.10', step='0.0.0.1', count=10, up=False)))
```

**Comment by ajbalogh** [comment]
The benefit is that an auto-generated class removes the user from the tedium of having to specify direction.

**Comment by ashutshkumr** [comment]
I just corrected the proposed snippet.

Isn't it more tedious in existing snippet ?
- `Increment` vs `Decrement`
- `choice='increment'` vs `choice='decrement'`
- `increment=Increment(` vs `decrement=Decrement(`

vs

in proposed snippet, all data structure, enum and attribute name remains the same except
- `up=True` vs `up=False`

**Comment by ajbalogh** [comment]
A good code generator will attempt to hide the choice (its the equivalent of polymorphism). 
What you are then left with is using an explicit Increment or Decrement class (intent is obvious to someone reading the code) and not having to specify up every time a counter pattern is needed.
That being said it can be more terse by specifying Counter and defaulting up to True.  Up=true appears to be the most common pattern.

This would result in the following:

```
    Flow.Pattern:
      description: >-
        A container for packet header field patterns.
        Possible patterns are fixed, list, counter, random.
      type: object
      required: [choice]
      properties:
        choice: 
          type: string
          enum: [fixed, list, increment, decrement, random]
        fixed:
          type: string
        list:
          type: array
          items:
            type: string
        counter:
          $ref: '#/components/schemas/Flow.Counter'
        random:
          $ref: '#/components/schemas/Flow.Random'

    Flow.Counter:
      description: >-
        A counter pattern that can increment or decrement.
      type: object
      properties:
        start:
          description: >-
            The value at which the pattern will start.
          type: string
        step:
          description: >-
            The value at which the pattern will increment or decrement by.
          type: string
        count: 
          description: >-
            The number of values in the pattern.
          type: number
        up:
          description: >-
            Determines whether the pattern will increment (true) or decrement (false).
          type: boolean
          default: true

```

**Comment by ajbalogh** [comment]
https://github.com/open-traffic-generator/models/commit/26085a9c19cad38f833191d7f1b6c791e26eaf8b

**Comment by ashutshkumr** [comment]
> A good code generator will attempt to hide the choice (its the equivalent of polymorphism).

Very True ! Had the same thought in my head going through all the models with choices :)

**Comment by ajbalogh** [comment]
A set of python classes is available that mirrors the model.

pip install abstract-open-traffic-generator

The tests that are part of the package demonstrate how to use them.
