### ISSUE TITLE
Consolidate related control plane state/actions into set_device_state api

### ISSUE THREAD

**Issue by PrasenjitAdhikary** [open-traffic-generator/models#245]

**Comment by ankur-sheth** [comment]
Addressed by PR 255?

**Comment by ankur-sheth** [comment]
Addressed by PR #255 ?

**Comment by vinjose** [comment]
I think this is a set of more granular (above what PR 255 addresses) state controls at device level and can be optional for 1.0.

**Comment by PrasenjitAdhikary** [comment]
> Addressed by PR #255 ?

Yes, this will be addressed with PR https://github.com/open-traffic-generator/models/pull/255.

**Comment by PrasenjitAdhikary** [comment]
Closing this issue (as this will be addressed as part of PR https://github.com/open-traffic-generator/models/pull/255).

**Comment by ashutshkumr** [comment]
Reopening as this is an issue (which fixes the PR linked here)

**Comment by ashutshkumr** [comment]
Closed by https://github.com/open-traffic-generator/models/pull/305
