### ISSUE TITLE
Need support for misdirected packets in port results

### ISSUE THREAD

**Issue by razvanstan27** [open-traffic-generator/models#25]
I need support to verify traffic received ok (expected rx port received all transmitted packets and all other ports not in the flow did not receive any packet)

**Comment by ajbalogh** [comment]
Use the following steps to find misdirected packets (verify all ports in a configuration that are not participating in a flow haven't received any configured flow packets):
- Setup a capture object filtering for a unique flow field and add all ports to the capture that are not participating in the flow.
- Start capture then start transmit
- Once transmit is complete, retrieve the captures and verify that there are no packets captured.
