### ISSUE TITLE
Need support to add Manual Gateway mac in IPv4 stack

### ISSUE THREAD

**Issue by selldinesh** [open-traffic-generator/models#260]
We need a feature that is to disable resolve gateway checkbox in IPv4 stack and enter manual gateway Mac  in IPv4 stack which is the requirement for a use case in DASH project

If this can't be done, need a way to edit the mac address in the packet from the endpoint settings in traffic item

**Comment by selldinesh** [comment]
Hi @ANISH-GOTTAPU 
We are trying to create a vxlan config for DASH project where in the config needs the manual entry of the MAC on the ethernet stack of the smart NICs used in the topology, which is used for control plane and data plane aspect of the config

**Comment by ashutshkumr** [comment]
@selldinesh thanks for the details, but it only explains what needs to be done and not why it needs to be done.


We need to document in details why users may need to enter gateway mac manually regardless of whether they’re using a vxlan config or not.

**Comment by selldinesh** [comment]
normally traffic will be sent to the mac of the interface. but in our sonic datacenter scenario in order to implement redundancy, they do not care on what interface the traffic is being received, so the packets are always sent to the device mac not the interface mac.
https://github.com/sonic-net/SONiC/wiki/Configuration
{

"DEVICE_METADATA": {
        "localhost": {
        "hwsku": "Force10-S6100",
        "synchronous_mode": "disable",
        "default_bgp_status": "up",
        "docker_routing_config_mode": "unified",
        "hostname": "sonic-s6100-01",
        "platform": "x86_64-dell_s6100_c2538-r0",
        "mac": "4c:76:25:f4:70:82",
        "default_pfcwd_status": "disable",
        "bgp_asn": "65100",
        "deployment_id": "1",
        "type": "ToRRouter"
    }
  }
}
from our side only way we were able to do this was to disable arp and set manual gateway mac as the mac of the device
"mac": "4c:76:25:f4:70:82",
also the traffic is not sent to the IP of the physical interface it is sent to the ip of the loopback interface.

**Comment by ankur-sheth** [comment]
@selldinesh what happens if the packets are sent to the interface MAC?  Does the device drop them?

**Comment by mgheorghe** [comment]
it's not quite dropped but does not reach the proper processing unit, they may be sent to the port cpu instead of being processed by the asic, dif hw dif implementations.
