### ISSUE TITLE
Behavior of SetConfig and SetProtocolState needs to be clearly defined

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/models#270]
### What's concerning ?
1. Often times, it's not very clear as to what activity is performed as part of `SetConfig` and `StartProtocols`. e.g. current understanding is interface creation and MAC learning will happen as part of former, while bringing up router sessions will happen as part of latter.
2. For most common use cases, `StartProtocol` seems like a redundant step. e.g. it seems intuitive to create and start all configured entities inside `config.devices` right after executing `SetConfig`.
3. Configuration on most switches/routers mimic example behavior described in 2.

### Why would one still want a separate API to control state of device sub-entities (i.e. protocols/interfaces) ?
1. `Allow interception` before any control-plane protocol negotiation happens. e.g.
    * Start Capture before BGP sessions are coming up
    * Start Capture before interface neighbor's MAC resolution happens
    * Simulate link down on some LAG-member ports before starting LACP
2. `Allow failing early / debugging` instead of waiting for final failure. e.g. from scenarios seen in SONiC tests,
    * Instead of waiting for BGP sessions to be up, one might want to just create interfaces and learn neighbor MAC to ensure the input gateway IPs are correct and then proceed with bringing BGP sessions up.
    * Instead of starting all BGP peers, one might want to bring them up each one of them in isolation
3. `Allow stopping` certain device sub-entities without actually cleaning them up.

### Possible solution ?
1. We could introduce a global option in config to indicate that all device sub-entities should be created/started upon `SetConfig`. Default behavior would be to `start all`.

   ```go
   // do not start interfaces/protocols upon SetConfig
   config.Options().DeviceOptions().SetAutoStart(false)
   ```
2. The global option should be limited to starting `ALL` or `NOTHING`. Anything in between should ideally be controlled by a separate API call.
3. To be very consistent, following will need to be done as part of a separate API call when the user opts-in to disable the global option.
    * All actions that require neighbor info learning before starting routing protocols (ARP/ND)
    * L2 protocols (e.g. LLDP / LACP)
    * All routing protocols
4. The separate API could be called `SetControlState` and will need to replace `SetProtocolState` in order to allow flexibility of granularly modifying states of each and every relevant device sub-entities. Needs to be discussed further in https://github.com/open-traffic-generator/models/pull/255.

> NOTE: More needs to be discussed on behavior of 4 in terms of layer dependency. e.g. should choosing to start BGP sessions automatically create corresponding ip interfaces ? 

### Alternatives considered
1. Introduce `auto_start` boolean for each and every single device sub-entity and facilitate repeated config pushes via `UpdateConfig` API. e.g. `SetConfig` with `auto_start` initially set to `false` for all, followed up `UpdateConfig` with `auto_start` set to `true` for interfaces only, so on and so forth.
2. The major drawback of this approach is switching between "common use-case" and "debug use-case" requires a lot of modification in config itself.

**Comment by bortok** [comment]
For consideration, if we want to enable autostart of interfaces & L2, but keep certain L3 protocols under `SetControlState`, the following could be used:

```Go
// start all device protocols upon SetConfig
config.Options().DeviceOptions().SetAutoStart(true)
// but do not start BGP upon SetConfig
config.Options().DeviceOptions().Bgp().SetAutoStart(false)
```

**Comment by ashutshkumr** [comment]
MOM from another round of meetings:

### SetConfig / StartProtocol Behavior
- We’ll have a global option in config, set to true by default, to start ALL interfaces/routers/protocols upon SetConfig
- When explicitly set to false, interface creation, neighbor info learning, protocol bring-up, etc. will be done upon StartProtocols
- If user calls StartProtocols even after setting the global option to true (which will start protocols upon SetConfig), they’ll just get a warning that protocols are already started

Hence, model and implementation changes are needed, although it won’t break the existing tests.
 
There will however be breaking changes, done separately, regarding control API consolidation, where StartProtocols shall be replaced with SetDeviceState, allowing more granular control on starting each device sub-entity.

### StartTraffic Behavior
The most reliable way for the users is still to poll for learned info readiness before starting traffic (consisting of flows that requires learned info) because of following reasons:
- In some cases, learned info readiness on OTG-only (and not DUT side), does not guarantee that packets will be forwarded.
- The issue associated with users having to poll for learned info has so far has not been reported by any customer. So we don’t have enough justification/ask yet to provide an alternate approach here.

**Comment by lemoncrust** [comment]
How do you _stop_ it? How to you start it again after you stopped it? SetAutoStart just feels narrow - 'start the protocol, but only if you just started the test'. I would still think you need something generally consistent.

**Comment by ashutshkumr** [comment]
@lemoncrust another alternative to `SetDeviceState` API would be to introduce "declarative flag" for each and every individual node inside the `device` tree (e.g. ethernets, ips, bgp routers, is-is routers, etc).

This approach would result in more daunting UX because:
- How would you start/stop certain objects in the device tree multiple times ? Update "declarative flag" for each object inside the config and call `UpdateConfig`.
- If one wants to capture control packets or do some instrumentation before starting devices, one would have to push initial config with all "declarative flags" enabled, start capture, then update config - The flaw in the workflow here is that when debugging, one would end up modifying the configuration
- For fairly large config, we're end up sending the blob every time

**Comment by ashutshkumr** [comment]
@lemoncrust to summarize.

This proposal:
- Describes the introduction of `AutoStart` flag to automatically start all protocols on SetConfig itself.
- Briefly describes what should be done as part of `SetConfig` call when that flag is set/unset.

This works well with the existing `SetProtocolState` API as it allows explicitly starting/stopping all protocols.
Based on more details provided in the issue, we plan to eventually replace `SetProtocolState` with more flexible `SetDeviceState` to allow starting/stopping subset of nodes in device tree .

**Comment by ashutshkumr** [comment]
@parthpower any suggestions from your end ?
