### ISSUE TITLE
'Reserved' field in IPv4 Header

### ISSUE THREAD

**Issue by indraniBh** [open-traffic-generator/models#28]
"What is 'reserved' field in ipv4 header format? Also "options" field is missing in the header."

**Comment by ajbalogh** [comment]
Ipv4 packet defines flags field as 3 bits: reserved, dont_fragment, more_fragments
Rather than having users figure out what bit to set in a single flags field the field is broken out into those 3 fields. 
If you require options for a specific use case please add a separate issue.

**Comment by ajbalogh** [comment]
Add descriptions to ipv4 packet header fields.

**Comment by ajbalogh** [comment]
options will not be included at this time as there is no customer request for this field.

**Comment by ajbalogh** [comment]
implemented 3d4579c6201eb7af90076088ad3517f4bdacbccc
