### ISSUE TITLE
We should support only one Rx port for each flow

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/models#29]
@ankur-sheth @winstonliu1111 @ajbalogh 

We specifically opted out of `meshing` and `bidirectional` config to make sure:
- User doesn't have to guess how each flow will be further broken down to multiple other flows
- User doesn't have to guess the actual number of flows they're working with and stats associated with each (because there's a cap on max flow count)
- `meshing` and `bidirectional` config can still be pro-grammatically achieved

So, why should we still expect list of Rx port names instead of a single Rx port name for each flow ?
```python
# multiple rx port names per flow
flows=[Flow(name='f1', tx_rx=FlowTxRx(tx_port_name='p1', rx_port_names=['p2', 'p3']))]

# single rx port name per flow
flows=[
    Flow(name='f1', tx_rx=FlowTxRx(tx_port_name='p1', rx_port_name='p2')),
    Flow(name='f2', tx_rx=FlowTxRx(tx_port_name='p1', rx_port_name='p3'))
]
```

One possible answer is `Terse code`, but we could've achieved even terser code by including options for `multiple tx port names`, `meshing` and `bidirectional` config.

What other reasons do we have to expect `multiple rx port names` for each flow ?
Because, this IMO feels like a loose end that brings back the complexity that I mentioned above (first two points).

**Comment by ajbalogh** [comment]
I agree. I will change the rx_port_names to single rx_port_name.

**Comment by winstonliu1111** [comment]
Think about multicast?  Do we want to model a single flow that will get replicated to two different rx ports as two separate flows?

**Comment by winstonliu1111** [comment]
Just reopening it for now to make sure we all consider mcast?

**Comment by ajbalogh** [comment]
The tx_rx is a choice - right now it supports PortTxRx, DeviceTxRx - the design is meant to be extensible and should support a MulticastPortTxRx for that and have specific documentation in that object as opposed to the PortTxRx

**Comment by winstonliu1111** [comment]
Sounds reasonable.

**Comment by winstonliu1111** [comment]
@ashutshkumr @ankur-sheth any comments on the way to handle multicast?  if you guys also think it is reasonable, we can close this.

**Comment by ankur-sheth** [comment]
I'm not sure that we want a separate MulticastPortTxRx.  That said, multicast doesn't seem like a common use-case.  Can you give me an example of a use-case where we are sending/receiving multicast traffic?  IGMP?

**Comment by ashutshkumr** [comment]
Do we need to multicast against:
1. Test ports (traffic engine interface) ?
2. Interfaces belonging to SUT ?
3. Emulated interfaces ?

I'm asking this because we'll need multiple rx port names only for **(1.)** and the concern is how are we (or who is) going to assign multicast group to each test interface (or if it is even feasible).

Hence, at this point, I do not have enough information to comment on whether we need MulticastPortTxRx. 

For **(2.)**, just embedding desired multicast addr in frame should be fine. Interestingly, this also tells us that there are scenarios when we might want `rx_port_name` to be optional.

**(3.)** should be taken care of by DeviceTxRx.

**Comment by ankur-sheth** [comment]
I went thru this thread again.  I'm ok to add MulticastPortTxRx if and when required.  For now, we are ok to support only one Rx port/device for each flow.  We can close it as earlier and open a new issue when we need to support multicast.  

@ajbalogh @ashutshkumr @winstonliu1111 sound ok to you?

**Comment by winstonliu1111** [comment]
sounds good to shelve it, we've got a number of ideas in the discussions if/when this ever comes up again.
