### ISSUE TITLE
Allow otg BGP implementation to report FSM states. 

### ISSUE THREAD

**Issue by apratimmukherjee** [open-traffic-generator/models#295]
Currently otg BGP metric ( https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/open-traffic-generator/models/master/artifacts/openapi.yaml&nocors#tag/Metrics/operation/get_metrics) only has attribute session_state which returns whether the implementation is in up or down state. 
When session state is checked via otg-gnmi , this is mapped to Idle or Established state ( https://github.com/open-traffic-generator/models-yang/blob/main/models/bgp/open-traffic-generator-bgp.yang ) 
The full list of states defined here are : 
IDLE , CONNECT , ACTIVE , OPEN_SENT , OPEN_CONFIRM,   ESTABLISHED

This causes confusion since underlying BGP implementation when in any on the non -'up' states gets mapped to IDLE which caused a lot of confusion on why the test  port is not moving at least to CONNECT or ACTIVE state even if peer port is misbehaving. 

To address this and carry the full information to gnmi module including the sub-states between IDLE and ESTABLISHED, we need to add a new fsm_state in otg metrics for bgpv4 and bgpv6 so that it can return the full and correct information via otg-gnmi to match openconfig expectation. 
_" What I'm noticing when I do a gNMI subscribe on /bgp-peers/bgp-peer[name=*]/state/session-state is that the session state is always **_IDLE_**. I'm expecting it to become **_ACTIVE_** and thus actively trying to establish a connection. "_ -> This is what Wen Bo Li reported when trying to bring up test port BGP session with lemming openconfig fake DUT implementation ( where BGP was actually not coming up due to issue with port number being used by lemming ) .

**Comment by SouravSinhaRoy** [comment]
the issue is fixed and implemented in release [Ixia-c v0.0.1-3768](https://github.com/open-traffic-generator/ixia-c/releases/tag/v0.0.1-3768)
