### ISSUE TITLE
How does one provide custom payload without explicitly providing offset ? FlowCustom has some limitations.

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/models#3]
This is what I intended to do:

```python
packet=[
    FlowHeader(choice='ethernet', ethernet=FlowEthernet()),
    FlowHeader(choice='ipv4', ipv4=FlowIpv4()),
    # this is completely made up and not a part of spec
    # but it's supposed to assign a stream of 10 'AB' (and repeat the same until it hits the checksum offset) 
    FlowHeader(choice='payload', custom=FlowPayload(choice='hexstr', hexstr='AB'*10))
]
```

Although it's technically incorrect to specify `payload` as a `FlowHeader` container, but let's assume that we're allowed to do that for now. The closest thing I could find was `FlowCustom`. But I encountered some limitations.

```python
# According to spec, this will overlay the bytes from first offset of ethernet fragment.
FlowCustom(bytes='AB'*10)
# This does the job, but I have to explicitly specify the start offset of payload
FlowCustom(patterns=[FlowBitPattern(choice='bitlist', bitlist=FlowBitList(offset=34, values='AB'*10)])
# This also does the job, but it has length limitation and also requires start offset.
FlowCustom(patterns=[FlowBitPattern(choice='bitcounter', bitcounter=BitCounter(offset=34, ...)])
```

I believe it's important for user to not have to deduce payload offset when specifying custom payload.

**Comment by ajbalogh** [comment]
Custom is just that - a custom packet header that consists of x number of bytes.
It gets inserted into the packet based on its location and it can be inserted multiple times.
So you can have packet=[Ethernet(), Vlan(), Custom(bytes='...'), Tcp(), Custom(bytes='...')] 
The bit pattern offsets are only specific to the containing Custom packet header.
This allows the packet blaster / negative testers  to generate whatever they want.

**Comment by ashutshkumr** [comment]
Then how does one provide custom payload without having to explicitly provide payload offset ? (it's a pretty common use case in most traffic generators, including Ixia and Scapy)

Maybe a new schema for that is in works ? If not, I would propose to explore options to reuse `Custom`.
