### ISSUE TITLE
BGP Graceful Restart capabilities

### ISSUE THREAD

**Issue by jorgeneteng** [open-traffic-generator/models#317]
Add onto BGP Graceful Restart capabilities through API for both IPv4 and IPv6.

BGP Graceful Restart capabilities to add
-Enable LLGR (Disable as well)
-Act as restarted
-Advertise End-Of-RIB
-Stale Time

RFC 4724

**Comment by apratimmukherjee** [comment]
@jorgeneteng : When GR capability is enabled , we automatically enable End-Of-RIB marker in the implementation. Currently we have not exposed a knob to specifically allow enabling/disabling for End-Of-RIB

**Comment by apratimmukherjee** [comment]
Thanks @jorgeneteng for confirming. Closing the issue.
