### ISSUE TITLE
Result.CaptureRequest should contain firstFrame and lastFrame as optional argument

### ISSUE THREAD

**Issue by rudranil-das** [open-traffic-generator/models#32]
Along with port_name (mandatory field), firstFrame and lastFrame should be added as optional field(s) because user might be interested in getting a subset of packets received as captured result.
When only port_name is given, all the packets should be returned in captured result.

**Comment by ajbalogh** [comment]
The only thing returned is a stream of captured bytes - there should be no additional processing of the capture bytes on the server side as this just increases scope creep - this should be done by the client script.

**Comment by rudranil-das** [comment]
@ajbalogh 

Please consider the following use-case and possible options to address it as mentioned below,

Use-case: The user has created a flow with e.g. 100k packets and wants to get capture of e.g. first 10 packets.

Option 1: with the current model, like you proposed,
    Step a> Controller receives from Traffic Engine, byte-stream for the capture of all 100k packets. 
	Step b> Controller transfers the byte-stream (in raw or pcap format) to client-script for all 100k packets. 
	Step c> Client script (with help of some utility maybe) filters first 10 packets from byte-stream of 100k packets.
	
Option 2: using firstFrame=1 and lastFrame=10 in model,
    Step a> Controller receives from Traffic Engine byte-stream for the capture of only the first 10 packets. 
	Step b> Controller transfers the byte-stream (in raw or pcap format) to client-script for only the first 10 packets.
	Step c> Client script directly uses the byte-stream received.
	
The benefit of (Option 2) over (Option 1), 
1> there would be significantly less usage of bandwidth if we compare steps (a) and (b).
2> there is no additional processing with (Option 2) on the Controller side.
3> the effort spent to further filter packets in (step c) is not present in (Option 2).

@ankur-sheth @winstonliu1111
Please share your thoughts as well.

**Comment by ajbalogh** [comment]
Adding those options to make the API fit the use case opens the door for API creep.
The first option should be adjusted to send only 10 packets and the capture will return 10 packets.

**Comment by ashutshkumr** [comment]
Reopening per further discussion with @ankur-sheth .

Concerns raised by @ajbalogh make sense and we further need to explore if we can draw parallels with `tcpdump` on various use case. One such use case is where users might only want to collect last 10 or first 10 packets. e.g. `tcpdump -i eth0 -c 10`

**Comment by ashutshkumr** [comment]
Final design is different from what we had discussed here.

https://github.com/open-traffic-generator/models/releases/tag/v0.6.4
