### ISSUE TITLE
ATE Feature: BGP Link-bandwidth extended community

### ISSUE THREAD

**Issue by sugrimov** [open-traffic-generator/models#339]
Need support for BGP Link-bandwidth extended community.
Ref: https://www.ietf.org/archive/id/draft-ietf-idr-link-bandwidth-07.txt

**Comment by apratimmukherjee** [comment]
Please use the methods provided in https://github.com/open-traffic-generator/models/pull/332.
This is available for both ixia-c and h/w in latest ixia-c builds.
