### ISSUE TITLE
GroupBy field should be guided by enum choices and be part of flow configuration instead of Header configuration

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/models#4]
To track flows using `source MAC addr` and `source IP addr`, here's how currently it's done:
```python
packet = [
    FlowHeader(choice='ethernet', ethernet=FlowEthernet(), group_by=[FlowGroupBy(field='src', label='Source MAC Addr')]),
    FlowHeader(choice='ipv4', ipv4=FlowIpv4(), group_by=[FlowGroupBy(field='src', label='Source IP Addr')),
]
```

Problems are:
- There's no implicit validation on what could be accepted as field names to be tracked with
- To distinguish between two field names, we end up providing separate `label`
- It's a bit tedious to specify group_by in each header - subjective
- Usage of `track_by` vs `group_by` - subjective

We could essentially configure it as part of `Flow` instead of `Header`, so that all the fields can be provided in one place. (It also goes along well with how we return group_by stats - i.e. they're *directly* contained within flow stats itself)
In fact, we could define a list of ENUMs which will be descriptive enough and not require `label` input.

```python
FlowFlow(
    packet=[
        FlowHeader(choice='ethernet', ethernet=FlowEthernet()),
        FlowHeader(choice='ipv4', ipv4=FlowIpv4()),
    ],
    # fields is a list of enums
    tracking=Tracking(fields=['src_mac_addr', 'src_ip_addr'])
)
```

Lastly,  `TrackBy` or `GroupBy` should be extensible to include stats with custom offsets (e.g. group by values belonging to offset 16-18) and basic latency configuration (this is not a hard requirement in first phase as I understand).

e.g.
```python
Tracking(
    fields=['src_mac_addr', 'src_ip_addr', 'custom'],
    # configure two latency bins
    latency=Latency(
        method='cut_through',
        bins=[
            LatencyBin(min=10, max=100),
            LatencyBin(min=1000, max=10000)
        ]
    ),
   custom=SomeContainer(...)
)
```

**Comment by ajbalogh** [comment]
Every packet header field takes a pattern - that pattern offers an option to specify a ingress_tracking_name. The existence of the unique name indicates the field is to be tracked and the name is also what is seen in the flow_results.
Latency bins should be opened as a separate issue and marked as an enhancement.

The Flow.Pattern includes the following:
```
ingress_result_name:
          description: >-
            A unique name is used to indicate to the system that the field may 
            extend the result row key and create an aggregate result row for 
            every unique ingress value.
            To have ingress columns appear in flow result rows the flow result
            request allows for the ingress_result_name value to be specified
            as part of the request.
          type: string
```
