### ISSUE TITLE
Add support for PPP and IGMP packet headers

### ISSUE THREAD

**Issue by dgalan-xxia** [open-traffic-generator/models#45]
Add support for adding/configuring  protocol templates in /ixnetwork/traffic/trafficItem/<>/configElement/<>/stack

**Comment by ajbalogh** [comment]
Hi Diana, please provide the names of the packet headers you would like to have modeled.

**Comment by dgalan-xxia** [comment]
Hi Andy, please implement support for PPP and ICMP

**Comment by dgalan-xxia** [comment]
Andy, sorry, I meant IGMP

**Comment by ajbalogh** [comment]
implemented
