### ISSUE TITLE
Why is packet a list of headers and not a key-value pair ?

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/models#6]
*NOTE:* I am not requesting a fix here yet, just wanted to discuss some possibilities.

Currently we describe packet headers like so:
```python
packet=[
    FlowHeader(choice='ethernet', ethernet=FlowEthernet()),
    FlowHeader(choice='vlan', vlan=FlowVlan()),
    FlowHeader(choice='vlan', vlan=FlowVlan()),
    FlowHeader(choice='ipv4', ipv4=FlowIpv4()),
]
```

An alternative could be:
```python
packet = Packet(
    ethernet=FlowEthernet(),
    vlans=[FlowVlan(), FlowVlan()]
    ipv4=FlowIpv4()
)
```

Since all fields in `Packet` are null-able, it may not require explicit `choice` input. Moreover, its structure is very similar to `FlowHeader`, except it accepts multiple parameters. So it's terser in config and more compact on wire.

In fact, I can access fields like so: `packet.ethernet.src.fixed`
 
But all that can be considered to just be a gimmick. Hence, what advantages does former has over latter ?

**Comment by ajbalogh** [comment]
key/value pair doesn't denote order whereas the list of headers does (its also documented in the model)
```
 packet:
          description: >-
            The packet is a list of traffic protocol headers.
            The order of traffic protocol headers assigned to the list is the
            order they will appear on the wire.
```

**Comment by ajbalogh** [comment]
A note on the everything is nullable unless there is a default - it is done that way to reduce overhead in that if a user doesn't fill in something they don't care what the traffic generator assigns to it, if a user is concerned about the value they will fill it in. This allows for the concept of auto generated fields, learned info fields etc.
