### ISSUE TITLE
Provide examples for all possible nodes

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/models#76]
There's a team in India who are trying to run fuzzed testing on OTG API and what they need is that all examples be available for most nodes.

There are two known problems:
- The way we bundle and generate openapi.yaml will result in some nodes that do not contain any examples (we use x-extensions to generate some nodes on the fly)
- The way openapi generates examples does not reflect the correct format of the payload.

We can fix first problem. We can't fix second problem, but it definitely will affect the correctness.

**Comment by ajbalogh** [comment]
I disagree as the openapi.yaml is the end product after pre processing the x- extensions.  The only remaining extensions are x-constants which are there for language generators that want to take add syntactic sugar.
The tests being run should be executed on the consolidated openapi.yaml document - not the individual .yaml files.

**Comment by ajbalogh** [comment]
Prior to any changes being made to models, the team that is doing fuzzing testing should make its methodology public.

**Comment by ashutshkumr** [comment]
The team is using bundled yaml only. This will be fixed to a great extent after merging x-field-pattern branch (and the other one for devices) - since we're explicitly setting defaults there for each header field.

But we'll need to manually make changes in other remaining areas. e.g.

```json
  "flows": [
    {
      "tx_rx": {
        "choice": "port",
        "port": {
          "tx_name": "string",
          "rx_name": "string"
        },
```

should be
```json
  "flows": [
    {
      "tx_rx": {
        "choice": "port",
        "port": {
          "tx_name": "tx",
          "rx_name": "rx"
        },
```

**Comment by ajbalogh** [comment]
Why wouldn't the test app just generate defaults based on name and type? In the case of a flow name which should be unique it doesn't make any sense to have a default.

**Comment by raj91287** [comment]
@ajbalogh  We are using this https://github.com/microsoft/restler-fuzzer to generate the fuzzed api calls. This uses its own compiler/generator to generate those rest calls.

This tool needs those examples to have a better coverage. Trying to generate those examples would be like tweaking this tool to a great deal. Also, it might not get us a better coverage, if we keep of fuzzing based on the fixed examples generated on name and type, we might keep fuzzing in the local minima or maxima.

**Comment by ashutshkumr** [comment]
Per confirmation from @raj91287 this is addressed in latest versions of OTG models.
