### ISSUE TITLE
Ability to specify packet payload

### ISSUE THREAD

**Issue by ankur-sheth** [open-traffic-generator/models#8]
We need a way to specify the contents of the packet.  Say a packet is 1024 bytes and all I've done is added Ethernet and IP headers to it.  My understanding is that the rest of the packet is not specified in the API and will be implementation dependent.  Do we need a way for the user to describe the contents of the rest of the packet?

**Comment by ajbalogh** [comment]
Custom packet header is meant to be used anywhere for as many times as you want.

```
Flow(name='custom 128 byte payload all zeroes', 
    packet=[
	    Header(Ethernet()), 
		Header(Ipv4()), 
		Header(Custom(bytes='00' * 128))
	])
```
