### ISSUE TITLE
How do wefetch flow's transmit state[(same with capture/protocol state)]

### ISSUE THREAD

**Issue by Debarati-Chakraborty** [open-traffic-generator/models#9]
Need API for fetching flow's transmit state for cases where next action is executed depending upon the learned traffic state. 
The supported columns do not enlist state of traffic for Result.FlowRequest currently.

**Comment by ajbalogh** [comment]
added state to flow results.
capture state can be found under port results
device state has not yet been modeled - at this time there is no need for device state, learned information as those operations should be part of configuration or start transmit.
