### ISSUE TITLE
Provide support to configure manual gateway MAC inside LACP

### ISSUE THREAD

**Issue by kamalsahu0001** [open-traffic-generator/models#97]
Currently we don't have the support to configure manual gateway inside LACP.

**Comment by kamalsahu0001** [comment]
Currently customer is running IPv4 session on top of LAG. While running his scripts, he sees that sometimes the IPv4 sessions are not coming up. 
In order to debug the issue, he wants to bring the IPv4 session up by configuring the manual gateway MAC inside IPv4.
Even though he is using raw flows to send the traffic, he sees loss intermittently. So he wants to make sure that arp is getting resolved before sending the traffic.

**Comment by ashutshkumr** [comment]
@kamalsahu0001 the fixes for this will preferably be made in `snappi` instead of `abstract-trafffic-generator` (older API which MSFT was previously using).

Could you please confirm if it's ok to proceed with change in `snappi` ?

**Comment by ajbalogh** [comment]
This doesn't seem to be the correct solution to the problem.  The problem is that there is no way using the API/models to determine if the LAG/LACP is up or down. The workaround was to bring up an IPV4 session where the proper solution should be to check LAG/LACP metrics instead.

**Comment by ashutshkumr** [comment]
This can now be debugged using LACP states
